name: Python Test Automation

on:
  # Trigger on push to 'main' branch and pull requests targeting 'main'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Schedule the workflow to run every 24 hours
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow at midnight UTC every day

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_server.py

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./tests/test-results/
