name: Python Test Automation

on:
  # Only trigger the workflow based on the schedule
  schedule:
    - cron: "5 1 * * *"  # Runs at 8:05 PM Philadelphia time during standard time (EST, UTC-5)

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_server.py

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: test-results
          path: ./tests/test-results/
